---
title: "STAT 462 Final Project"
author: "Eric Wu"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
# Load necessary Libraries
library(tidyverse)
library(ggplot2)
library(janitor)
library(kableExtra)

# Load Dataset 
data <- read.csv("insurance.csv")
```

# Group Memeber

# Background

# Exploratory Data Analysis
```{r}
# Check for Null Value
print(sum(is.na(data)))

# Create dummy variable
dummy_data <- data %>%
  mutate(
    is_male = if_else(sex == "male", 1, 0),
    is_smoker = if_else(smoker == "yes", 1, 0),
    is_southwest = if_else(region == "southwest", 1, 0),
    is_southeast = if_else(region == "southeast", 1, 0),
    is_northwest = if_else(region == "northwest", 1, 0),
    is_northeast = if_else(region == "northeast", 1, 0)
  ) %>%
  select(-sex, -smoker, -region)

# Create standardized dataset for ML that requires scaling
scaled_data <- scale(dummy_data)
```

## Data Statistics

## Data Visualization

## LINE Assumption

# Model Building

## Multiple Linear Regression

## KNN Regression

## Random Forest

# Model Comparison

# Discussion

# Conclusion

# Code Appendix 


